<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1380349295906" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1380349295906">
    <message name="Request">
        <part name="fileName" type="xsd:string"/>
        <part name="fileLocation" type="xsd:string"/>
        <part name="fileType" type="xsd:string"/>
        <part name="size" type="xsd:int"/>
        <part name="lastModified" type="xsd:string"/>
        <part name="action" type="xsd:string"/>
    </message>
    <message name="Response">
        <part name="updated" type="xsd:int"/>
    </message>
    <portType name="PortType">
        <operation name="Operation">
            <input message="tns:Request"/>
            <output message="tns:Response"/>
        </operation>
    </portType>
</definitions>