<?xml version="1.0" encoding="UTF-8"?>
<!--Created by TIBCO WSDL-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1380349295906/OperationImpl" xmlns:jms="http://www.tibco.com/namespaces/ws/2004/soap/binding/JMS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jndi="http://www.tibco.com/namespaces/ws/2004/soap/apis/jndi" name="Untitled" targetNamespace="http://xmlns.example.com/1380349295906/OperationImpl">
    <wsdl:types/>
    <wsdl:service name="SendSOAPResponse">
        <wsdl:port binding="tns:SOAPEventSourceBinding" name="SOAPEventSource">
            <soap:address location=""/>
            <jms:connectionFactory>QueueConnectionFactory</jms:connectionFactory>
            <jms:targetAddress destination="queue">queue.DevOpsDemo</jms:targetAddress>
        </wsdl:port>
    </wsdl:service>
    <wsdl:portType name="PortType">
        <wsdl:operation name="Operation">
            <wsdl:input message="tns:Request"/>
            <wsdl:output message="tns:Response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SOAPEventSourceBinding" type="tns:PortType">
        <soap:binding style="rpc" transport="http://www.tibco.com/namespaces/ws/2004/soap/binding/JMS"/>
        <jms:binding messageFormat="Text"/>
        <wsdl:operation name="Operation">
            <soap:operation soapAction="/Processes/SendSOAPResponse" style="rpc"/>
            <wsdl:input>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://InputMessageNamespace" parts="fileName fileLocation fileType size lastModified action" use="encoded"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://OutputMessageNamespace" parts="updated" use="encoded"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="Request">
        <wsdl:part name="fileName" type="xs:string"/>
        <wsdl:part name="fileLocation" type="xs:string"/>
        <wsdl:part name="fileType" type="xs:string"/>
        <wsdl:part name="size" type="xs:int"/>
        <wsdl:part name="lastModified" type="xs:string"/>
        <wsdl:part name="action" type="xs:string"/>
    </wsdl:message>
    <wsdl:message name="Response">
        <wsdl:part name="updated" type="xs:int"/>
    </wsdl:message>
</wsdl:definitions>